[package]
name = "yahc"
version = "0.1.0"
authors = ["ducaale <sharaf.13@hotmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
atty = "0.2"
jsonxf = "1.0"
lazy_static = "1.4.0"
regex = "1"
reqwest = { version = "0.10", features = ["stream", "json", "gzip", "brotli"] }
rpassword = "5.0.0"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7"
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
tokio-util = {version = "0.3", features= ["codec"]}

[dependencies.syntect]
version = "4.4"
default-features = false
features = ["parsing", "html", "yaml-load", "dump-load", "dump-create", "regex-onig"]

[dev-dependencies]
assert_cmd = "1.0"
indoc = "1.0"

[build-dependencies]
syntect = { version = "4.4", default-features = false }
