[package]
name = "yahc"
version = "0.1.0"
authors = ["ducaale <sharaf.13@hotmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
regex = "1"
reqwest = { version = "0.10", features = ["blocking"] }
serde = "1.0"
serde_json = "1.0"
colored_json = "2"
ansi_term = "0.12"