[package]
name = "xh"
version = "0.7.0"
authors = ["ducaale <sharaf.13@hotmail.com>"]
edition = "2018"
license = "MIT"
description = "Yet another HTTPie clone"
documentation = "https://github.com/ducaale/ht"
homepage = "https://github.com/ducaale/ht"
repository = "https://github.com/ducaale/ht"
readme = "README.md"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0.38"
atty = "0.2"
jsonxf = "1.0"
encoding_rs = "0.8.28"
encoding_rs_io = "0.1.7"
indicatif = "0.15.0"
lazy_static = "1.4.0"
mime = "0.3.16"
mime2ext = "0.1.0"
regex = "1"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "stream", "json", "gzip", "brotli", "multipart", "blocking", "socks"] }
rpassword = "5.0.0"
serde_json = "1.0"
structopt = "0.3"

[dependencies.syntect]
version = "4.4"
default-features = false
features = ["parsing", "html", "yaml-load", "dump-load", "dump-create", "regex-onig"]

[dev-dependencies]
assert_cmd = "1.0"
assert_matches = "1.4.0"
indoc = "1.0"
predicates = "1.0.7"
httpmock = "0.5.5"
tempfile = "3.2.0"

[build-dependencies]
syntect = { version = "4.4", default-features = false }
